name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "Woolyenough"
        git config --global user.email "${{ secrets.EMAIL }}"
        git config pull.rebase false
        git pull
        rm -f release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git*'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "automated resource pack zip"
        git push --force
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
